class Emojis:
    x_emoji = '❌'
    tick_emoji = '✅'
    play_button = '▶️'
    reverse_button = '◀️'
    pause_button = '⏸'
    resume_button = '⏩'
    play_pause = '⏯️'
    stop_button = '⏹️'
    next_button = '⏭️'
    clipboard = '📋'
    music_note = '🎵'