{
  'connections': {
      # Dict format for connection
      'default': {
          'engine': 'tortoise.backends.asyncpg',
          'credentials': {
              'host': os.getenv('RDS_HOST'),
              'port': os.getenv('RDS_PORT'),
              'user': os.getenv('RDS_USER'),
              'password': os.getenv('RDS_PASSWORD'),
              'database': os.getenv('RDS_DB'),
          }
      },
  },
  'apps': {
      'models': {
          'models': ['src.data.db_context', 'aerich.models'],
          'default_connection': 'default',
      }
  },
}
